blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new',),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'post/your_post/$', views.your_post, name='your_post'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/edit/$', views.edit_comment, name='edit_comment'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls', namespace="blog")),
    url(r'^user/', include('user.urls', namespace='user')),
]

user/urls.py
"""Defines URL patterns for users"""
from django.conf.urls import url
from django.contrib.auth.views import login
from . import views

urlpatterns = [
	#Login page
	url(r'^login/$', login, {'template_name':'user/login.html'}, name='login'),
	
	#Logout page
	url(r'^logout/$', views.logout_view, name='logout'),

	#Register page
	url(r'^register/$', views.register, name='register'),
]

blog/models.py
from django.db import models
from django.utils import timezone

class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()
    
    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments')
    author = models.ForeignKey('auth.User')
    content = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.content

blog/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text')

class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ('content',)

user/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class UserCreateForm(UserCreationForm):
    """A form for register user which is inherited form UserCreationForm."""
    email = forms.EmailField(label="Email Address")

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        #Override save function
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()

        return user

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from .models import Post, Comment
from .forms import PostForm, CommentForm

@login_required
def your_post(request):
    posts = Post.objects.filter(author=request.user)
    return render(request, 'blog/your_post.html', {'posts': posts})

@login_required
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('blog:post_list')

def post_list(request):
    posts = Post.objects.order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts':posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    isAuthor = False
    if request.user == post.author:
        isAuthor = True
    return render(request, 'blog/post_detail.html', {'post': post, 'isAuthor':isAuthor})

@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)        
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment_to_post.html', {'form':form})

@login_required
def edit_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.created_date = timezone.now()
            comment.save()
            return redirect('blog:post_detail', pk=comment.post.pk)
    else:
        form = CommentForm(instance=comment)
    return render(request, 'blog/comment_edit.html', {'form':form})

@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form':form})

@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form':form})

user/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from .forms import UserCreateForm

def logout_view(request):
    """Logout"""
    logout(request)
    return HttpResponseRedirect(reverse('blog:post_list'))

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        #Display blank register form
        form = UserCreateForm()
    else:
        #Process completed form
        print(request.POST)
        form = UserCreateForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            print(form.cleaned_data)

            #Log the user and redirect to homce page.
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('blog:post_list'))
        else:
            messages.warning(request, 'Invalid form!')
    return render(request, 'user/register.html', {'form':form})

blog/templates/blog/add_comment_to_post.html
{% extends 'blog/base.html' %}
{% load bootstrap3 %}
{% block content %}
    <h1>New comment</h1>
    <div class="row">
        <form method="POST" class="post-form col-md-10">{% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="save btn btn-default">Send</button>
        </form>
    </div>
{% endblock %}

blog/templates/blog/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Django Girl's blog</title>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'-->
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>
    <body>
        <header class="navbar navbar-default navbar-static-top" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#myNavbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="/" class="navbar-brand">Django Girl's</a>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar" role="navigation">
                    <ul class="nav navbar-nav">
                        <li><a href="/">User</a></li>
                        <li><a href="/post/your_post">List Post</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li>
                                <p class="navbar-text"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>Signed in as {{ user.username }}</p>
                            </li>
                            <li>
                                <a href="{% url 'user:logout' %}"><span class="glyphicon glyphicon-off"></span>Logout</a>
                            </li>
                        {% else %}
							<li><a href="{% url 'user:register' %}">register</a></li>
							<li><a href="{% url 'user:login' %}">log in</a></li>
						{% endif %}
                    </ul>
                </div>
            </div>
        </header>
        <div class="bs-docs-header" id="content" tabindex="-1">
            <div class="container">
                <h1>DjangoGirl</h1>
                <p>Một sản phẩm tào lao được làm từ Django, Python & Gray Matter =)). Blog chỉ mang tính làm cho biết, nên có phần không được tỉ mỉ lắm.</p>
            </div>
        </div>
        <div class="content container"> 
            {% include 'blog/messages.html' %}
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>

blog/templates/blog/comment_edit.html
{% extends 'blog/base.html' %}
{% load bootstrap3 %}
{% block content %}
    <h1>Edit comment</h1>
    <div class="row">
        <form method="POST" class="post-form col-md-10">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="save btn btn-primary">Save</button>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/messages.html
{% if messages %}
  {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      {{ message }}
    </div>
  {% endfor %}
{% endif %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block content %}
    <div class="row">
        <div class="post col-md-10">
            <!-- Author -->
            <div class="author">
                {{ post.author }}
            </div>
            {% if post.published_date %}
                <div class="date">
                    {{ post.published_date }}
                </div>
            {% endif %}
            
            <h1>{{ post.title }}</h1>
            <p>{{ post.text|linebreaksbr }}</p>
            <hr>

            <!-- Comment -->
            <a class="btn btn-default" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add comment</a>
            {% for comment in post.comments.all %}
                <div class="comment">
                    <div class="author">
                        {{ comment.author }}
                    </div>
                    <div class="date">
                        <a href="{% url 'blog:edit_comment' pk=comment.pk %}"> {{ comment.created_date }}</a>
                    </div>
                    <p>{{ comment.content|linebreaks }}</p>
                    <hr>
                </div>
            {% empty %}
                <p>No comments here yet :(</p>
            {% endfor %}

        </div>
        
        <!-- dropdown button edit, delelte -->
        {% if isAuthor %}
            <div class="post col-md-2">
                <!-- dropdown-->
                <div class="dropdown">
                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                        <li ><a href="{% url 'blog:post_edit' pk=post.pk %}">Edit</a></li>
                        <li><a href="#delete" data-toggle="modal">Delete</a></li>
                    </ul>
                </div>

                <!--Popup confirm delete post-->
                <div class="modal fade" id="delete" data-target="#delete" role="dialog">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <h4 class="modal-title">Delete Confirm?</h4>
                            </div>
                            <div class="modal-body">
                                <p>Do you want to delete this post.</p>
                            </div>
                            <div class="modal-footer">
                                <a href="{% url 'blog:post_remove' pk=post.pk %}" role="button" class="btn btn-danger">Delete</a>
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}
{% load bootstrap3 %}
{% block content %}
    <h1>Edit post</h1>
    <form method="POST" class="post-form col-md-10">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="save btn btn-primary">Save</button>
    </form>
{% endblock content %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
    <div class="row">
        <div class="post col-md-10">
            <div class="author">
                {{ post.author }}
            </div>
            <div class="date">
                <a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.published_date }}</a>
            </div>
            <h1>{{ post.title }}</h1>
            <p>{{ post.text|linebreaksbr|truncatechars:500 }}</p>
            <hr>
        </div>
    </div>
    {% endfor %}
{% endblock content %}

blog/templates/blog/your_post.html
{% extends 'blog/base.html' %}
{% block content %}
    {% for post in posts %}
    <div class="row">
        <div class="post col-md-10">
            <div class="date">
                {{ post.published_date }}
            </div>
            <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|linebreaksbr }}</p>
            <hr>
        </div>
    </div>
    {% endfor %}
{% endblock content %}

user/templates/user/login.html
{% extends 'blog/base.html' %}
{% load bootstrap3 %}
{% block content %}
<div class="row">
    <form method="post" action="{% url 'user:login' %}" class="form-horizontal col-md-10" role="form">
		{% csrf_token %}
        {% bootstrap_form form %} 
        {% buttons %}
            <button type="submit" class="btn btn-primary-outline">Login</button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'blog:post_list' %}" />
    </form>
</div>
{% endblock content %}

user/templates/user/profile.html
{% extends 'blog/base.html' %}
{% block content %}
    
{% endblock content %}

user/templates/user/register.html
{% extends 'blog/base.html' %}
{% load bootstrap3 %}
{% block content %}
<div class="row">
    <form method="post" action="{% url 'user:register' %}" class="form-horizontal col-md-10">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary-outline">Register</button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'blog:post_list' %}" />
    </form>
</div>
{% endblock content %}